---
title: "Intro"
---

<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://durtal.github.io/KYDerby2015-twitter/index.html" data-text="Kentucky Derby 2015 Twitter Analysis, Intro" data-via="_RcappeR" data-related="_RcappeR" data-hashtags="rstats,KYDerby">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

Following on from my look at how racing fans interacted on twitter during the 2014 and 2015 Cheltenham Festival (see the [dedicated site](http://durtal.github.io/cheltenham-festival-2015-twitter/index.html)) and reading the following tweet by [\@railbird](https://twitter.com/railbird), I decided to adapt my code to collect tweets that use the popular [#KYDerby](https://twitter.com/search?q=%23KYDerby&src=typd) hashtag as well as the potential runners in the race itself.

<blockquote class="twitter-tweet" lang="en-gb"><p>Would love to see something like this for the 2015 <a href="https://twitter.com/hashtag/KYDerby?src=hash">#KYDerby</a>, <a href="https://twitter.com/TwitterData">@TwitterData</a>: <a href="https://t.co/oBrNY0JVVb">https://t.co/oBrNY0JVVb</a></p>&mdash; Railbird (@railbird) <a href="https://twitter.com/railbird/status/585128431060418563">April 6, 2015</a></blockquote>

This site will host some simple analysis and plots, everything, data, code, plots, are available in this [repo](https://github.com/durtal/KYDerby2015-twitter) and its various branches.  Any contributions, such as posts would be most welcome, get in touch [@\_RcappeR](https://twitter.com/_RcappeR).
